services:
  # Incident service DB
  incident-db:
    image: mysql:8.0.40
    container_name: incident-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=incidents_db 
    volumes:
      - incident-db-data:/var/lib/mysql
    networks:
      - backend-net

  # Incident backend
  incident-backend:
    image: ghcr.io/${REPO_OWNER}/${REPO_NAME}/incident-service:latest
    container_name: incident-backend
    restart: unless-stopped
    environment:
      - DB_URL=${INCIDENTS_DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - PORT=${INCIDENT_SERVICE_PORT}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - incident-db
      - config-server
    networks:
      - backend-net

  # User service DB
  users-db:
    image: mysql:8.0.40
    container_name: users-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=users_db 
    volumes:
      - user-db-data:/var/lib/mysql
    networks:
      - backend-net

  # User backend
  user-backend:
    image: ghcr.io/${REPO_OWNER}/${REPO_NAME}/user-service:latest
    container_name: user-backend
    restart: unless-stopped
    environment:
      - DB_URL=${USERS_DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - PORT=${USERS_SERVICE_PORT}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - users-db
      - config-server
    networks:
      - backend-net

  # Config server
  config-server:
    image: ghcr.io/${REPO_OWNER}/${REPO_NAME}/config-server:latest
    container_name: config-server
    restart: unless-stopped
    environment:
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_TOKEN=${GIT_TOKEN}
    networks:
      - backend-net

  # Service discovery
  service-discovery-server:
    image: ghcr.io/${REPO_OWNER}/${REPO_NAME}/service-discovery-server:latest
    container_name: service-discovery-server
    restart: unless-stopped
    networks:
      - backend-net

  # API Gateway
  api-gateway:
    image: ghcr.io/${REPO_OWNER}/${REPO_NAME}/api-gateway:latest
    container_name: api-gateway
    restart: unless-stopped
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    ports:
      - "8080:8080"
    networks:
      - backend-net

   frontend:
    build: ./frontend/frontend-app
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # Mount local source so changes mirror inside container
      - ./frontend/frontend-app/src:/opt/frontend-app/src
      - ./frontend/frontend-app/public:/opt/frontend-app/public
      # Keep node_modules inside container (avoid conflicts)
      - /opt/frontend-app/node_modules
    depends_on:
      - api-gateway


volumes:
  incident-db-data:
  user-db-data:

networks:
  backend-net:
    driver: bridge
