version: "3.9"

services:
  # Incident service DB
  incident-db:
    image: mysql:8.0.40
    container_name: incident-db
    restart: unless-stopped
    env_file: ./db/incident-db/.env
    ports:
      - "3307:3306"
    volumes:
      - ./db/incident-db:/docker-entrypoint-initdb.d   # init.sql + seed.sql
      - incident-db-data:/var/lib/mysql
    networks:
      - backend-net

  # Incident backend
  incident-backend:
    build: ./backend/incident-service
    image: incident-backend-img
    container_name: incident-backend
    restart: unless-stopped
    environment:
      - JWT_SECRET=${JWT_SECRET}
    env_file: ./backend/incident-service/.env
    ports:
      - "8085:8085"
    depends_on:
      - incident-db
    networks:
      - backend-net

  # User service DB
  users-db:
    image: mysql:8.0.40
    container_name: users-db
    restart: unless-stopped
    env_file: ./db/users-db/.env
    ports:
      - "3308:3306"
    volumes:
      - ./db/users-db:/docker-entrypoint-initdb.d   # init.sql + seed.sql for users
      - user-db-data:/var/lib/mysql
    networks:
      - backend-net

  # User backend
  user-backend:
    build: ./backend/user-service
    image: user-backend-img
    container_name: user-backend
    restart: unless-stopped
    environment:
      - JWT_SECRET=${JWT_SECRET}
    env_file: ./backend/user-service/.env
    ports:
      - "8082:8082"
    depends_on:
      - users-db
    networks:
      - backend-net

volumes:
  incident-db-data:
  user-db-data:

networks:
  backend-net:
    driver: bridge
