version: "3.9"

services:
  # Incident service DB
  incident-db:
    image: mysql:8.0.40
    container_name: incident-db
    restart: unless-stopped
    env_file: ./db/incident-db/.env
    volumes:
      - incident-db-data:/var/lib/mysql
    networks:
      - backend-net

  # Incident backend
  incident-backend:
    image: ghcr.io/${REPO_OWNER}/${REPO_NAME}/incident-service:latest
    container_name: incident-backend
    restart: unless-stopped
    environment:
      - JWT_SECRET=${JWT_SECRET}
    env_file: ./backend/incident-service/.env
    depends_on:
      - incident-db
      - config-server
    networks:
      - backend-net

  # User service DB
  users-db:
    image: mysql:8.0.40
    container_name: users-db
    restart: unless-stopped
    env_file: ./db/users-db/.env
    volumes:
      - user-db-data:/var/lib/mysql
    networks:
      - backend-net

  # User backend
  user-backend:
    image: ghcr.io/${REPO_OWNER}/${REPO_NAME}/user-service:latest
    container_name: user-backend
    restart: unless-stopped
    environment:
      - JWT_SECRET=${JWT_SECRET}
    env_file: ./backend/user-service/.env
    depends_on:
      - users-db
      - config-server
    networks:
      - backend-net

  # Config server
  config-server:
    image: ghcr.io/${REPO_OWNER}/${REPO_NAME}/config-server:latest
    container_name: config-server
    restart: unless-stopped
    env_file: ./backend/config-server/.env
    networks:
      - backend-net

  # Service discovery
  service-discovery-server:
    image: ghcr.io/${REPO_OWNER}/${REPO_NAME}/service-discovery-server:latest
    container_name: service-discovery-server
    restart: unless-stopped
    networks:
      - backend-net

  # API Gateway
  api-gateway:
    image: ghcr.io/${REPO_OWNER}/${REPO_NAME}/api-gateway:latest
    container_name: api-gateway
    restart: unless-stopped
    environment:
      - JWT_SECRET=${JWT_SECRET}
    env_file: ./backend/api-gateway/.env
    ports:
      - "8080:8080"
    networks:
      - backend-net

volumes:
  incident-db-data:
  user-db-data:

networks:
  backend-net:
    driver: bridge
